name: MineNG
version: '${version}'
main: br.com.mineng.commons.CommonsPlugin
api-version: '1.20'
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.23
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.23
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.15.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.15.0
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1-Beta