name: NGEssentials
version: '${version}'
main: br.com.mineng.ngessentials.NGEssentials
api-version: '1.20'
depend: [MineNG]
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.23
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.23
  - io.insert-koin:koin-core:3.5.3
  - io.insert-koin:koin-core-jvm:3.5.3